
development:
  adapter: mysql
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  database: rubyparis
  host: localhost
  username: root
  password: root

test:
  adapter: mysql
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  database: rubyparis
  host: localhost
  username: root
  password: root

production:
  adapter: mysql
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  database: rubyparis
  host: localhost
  username: root
  password: root
