
development:
  adapter: mysql
  database: rubyparis
  host: localhost
  username: root
  password: root

test:
  adapter: mysql
  database: rubyparis
  host: localhost
  username: root
  password: root

production:
  adapter: mysql
  database: rubyparis
  host: localhost
  username: root
  password: root
